/**
 * Decision Engine Types
 * 
 * Types for the decision-making layer of NOEMA.
 */

import type { MentalModel, Experience, Observation } from "../../schemas/index.js";
import type {
  BrowserAction,
  BrowserActionOutcome,
  BrowserActionType,
  DecisionOutput,
} from "./action_types.js";

// =============================================================================
// Decision Engine Configuration
// =============================================================================

export interface DecisionEngineConfig {
  /** Minimum model confidence to consider (default: 0.4) */
  modelConfidenceThreshold?: number;
  /** Maximum number of models to include in context (default: 5) */
  maxModelsInContext?: number;
  /** Maximum number of recent outcomes to include (default: 5) */
  maxRecentOutcomes?: number;
  /** Use mock LLM for testing (default: false) */
  mockLLM?: boolean;
  /** LLM provider configuration */
  llm?: {
    provider: "gemini" | "openai";
    model?: string;
    apiKey?: string;
  };
  /** Browser configuration */
  browser?: {
    headless?: boolean;
    slowMo?: number;
    screenshotDir?: string;
  };
}

// =============================================================================
// Test Credentials (loaded from environment variables for security)
// =============================================================================

export interface TestCredentials {
  /** Test username / email */
  username?: string;
  /** Test password */
  password?: string;
  /** Additional credential fields (e.g., API tokens, 2FA codes) */
  extras?: Record<string, string>;
}

// =============================================================================
// Decision Context
// =============================================================================

export interface DecisionContext {
  /** Current task description */
  task: string;
  /** Active mental models (filtered by confidence) */
  mentalModels: MentalModel[];
  /** Relevant experiences */
  experiences: Experience[];
  /** Recent action outcomes */
  recentOutcomes: BrowserActionOutcome[];
  /** Recent observations */
  recentObservations: Observation[];
  /** Current run ID */
  runId: string;
  /** Latest visual description from Gemini Vision (screenshot analysis) */
  visualContext?: string;
  /** Test credentials loaded from environment (never shown in narration) */
  credentials?: TestCredentials;
}

// =============================================================================
// Decision Result
// =============================================================================

export interface DecisionResult {
  /** The selected action */
  action: BrowserAction;
  /** Raw LLM output */
  rawOutput: DecisionOutput;
  /** Context used for decision */
  contextUsed: {
    modelIds: string[];
    experienceIds: string[];
    outcomeIds: string[];
  };
}

// =============================================================================
// Execution Result
// =============================================================================

export interface ExecutionResult {
  /** The action that was executed */
  action: BrowserAction;
  /** The outcome of execution */
  outcome: BrowserActionOutcome;
  /** Observations generated from outcome */
  generatedObservationIds: string[];
}

// =============================================================================
// Test Plan
// =============================================================================

export interface TestPlanStep {
  /** Step number (1-based) */
  step_id: number;
  /** Short title (e.g., "Login with valid credentials") */
  title: string;
  /** Detailed description of what to do */
  description: string;
  /** Ordered sub-steps within this test case (e.g., ["Navigate to login page", "Enter username", "Enter password", "Click Login"]) */
  test_steps?: string[];
  /** Specific expected results (e.g., ["User is logged in", "Products page is visible"]) */
  expected_results?: string[];
  /** Suggested primary action type */
  action_hint: string;
  /** What success looks like (summary) */
  expected_outcome: string;
  /** What failure looks like */
  failure_indicator: string;
  /** Priority level */
  priority: "critical" | "important" | "nice_to_have";
  /** Runtime: step result after execution */
  result?: "pass" | "fail" | "skipped";
  /** Runtime: what actually happened */
  actual_outcome?: string;
  /** Runtime: actions taken to complete this step */
  actions_taken?: number;
  /** Runtime: screenshot file paths captured during this step */
  screenshots?: string[];
}

export interface TestPlan {
  /** Human-readable title */
  plan_title: string;
  /** Why the plan was structured this way */
  plan_rationale: string;
  /** Ordered test steps */
  steps: TestPlanStep[];
  /** Total number of steps */
  total_steps: number;
  /** Estimated total actions across all steps */
  estimated_actions: number;
  /** Whether this plan was generated by LLM or built-in rule engine */
  generated_by: "gemini" | "built_in";
  /** Timestamp */
  created_at: string;
}

// =============================================================================
// LLM Prompt Input
// =============================================================================

export interface DecisionPromptInput {
  task: string;
  mental_models: {
    model_id: string;
    title: string;
    summary: string;
    confidence: number;
    procedures: string[];
    failure_modes: string[];
  }[];
  experiences: {
    experience_id: string;
    statement: string;
    confidence: number;
  }[];
  /** What you ALREADY DID — action type, selector, value, and outcome. Use this to avoid repetition. */
  recent_actions: {
    action_type: BrowserActionType;
    selector?: string;
    value?: string;
    rationale: string;
    status: "success" | "failure";
    error_message?: string;
  }[];
  recent_outcomes: {
    action_id: string;
    action_type: BrowserActionType;
    status: "success" | "failure";
    error_message?: string;
  }[];
  available_actions: string[];
  /** Visual description of the current browser page from Gemini Vision */
  visual_context?: string;
  /** Test credentials from environment (for form filling — NEVER log or narrate these) */
  credentials?: TestCredentials;
}
